apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "topolvm.fullname" . }}-node
  labels:
  {{- include "topolvm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "topolvm.fullname" . }}-node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "topolvm.fullname" . }}-node
      annotations:
        {{ if and .Values.node.metrics.enabled .Values.node.metrics.annotations }}
        {{ toYaml .Values.node.metrics.annotations | indent 8 }}
        {{ end }}
    spec:
      serviceAccountName: {{ template "topolvm.fullname" . }}-node
      containers:
        - name: topolvm-node
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          securityContext:
            {{- toYaml .Values.node.securityContext | nindent 12 }}
          command:
            - /topolvm-node
            - --lvmd-socket=/run/lvmd/lvmd.sock
          ports:
            - containerPort: 9808
              name: healthz
              protocol: TCP
            {{ if .Values.node.metrics.enabled }}
            - containerPort: 8080
              name: metrics
              protocol: TCP
            {{ end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            failureThreshold: 3
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 60
          resources:
            {{- toYaml .Values.node.resources | nindent 12 }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: node-plugin-dir
              mountPath: /run/topolvm
            - name: lvmd-socket-dir
              mountPath: /run/lvmd
            - name: pod-volumes-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
            - name: csi-plugin-dir
              mountPath: /var/lib/kubelet/plugins/kubernetes.io/csi
              mountPropagation: "Bidirectional"

        - name: csi-registrar
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /csi-node-driver-registrar
            - "--csi-address=/run/topolvm/csi-topolvm.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/topolvm.cybozu.com/node/csi-topolvm.sock"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/topolvm.cybozu.com /registration/topolvm.cybozu.com-reg.sock"]
          volumeMounts:
            - name: node-plugin-dir
              mountPath: /run/topolvm
            - name: registration-dir
              mountPath: /registration

        - name: liveness-probe
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /livenessprobe
            - "--csi-address=/run/topolvm/csi-topolvm.sock"
          volumeMounts:
            - name: node-plugin-dir
              mountPath: /run/topolvm

      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: node-plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/topolvm.cybozu.com/node
            type: DirectoryOrCreate
        - name: csi-plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/kubernetes.io/csi
            type: DirectoryOrCreate
        - name: pod-volumes-dir
          hostPath:
            path: /var/lib/kubelet/pods/
            type: DirectoryOrCreate
        - name: lvmd-socket-dir
          hostPath:
            path: /run/topolvm
            type: Directory
    {{- if .Values.node.tolerations }}
      tolerations:
{{ toYaml .Values.node.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.node.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.node.nodeSelector | indent 8 }}
    {{- end }}
